DataSource.destroy_all

data_sources = [
  {
    source: :pga,
    stat: 'Putting from 3',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.341.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_3_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 3',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.341.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_3_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 4',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.342.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_4_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 4',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.342.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_4_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 5',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.343.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_5_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 5',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.343.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_5_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 6',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.344.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_6_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 6',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.344.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_6_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 7',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.345.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_7_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 7',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.345.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_7_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 8',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.346.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_8_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 8',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.346.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_8_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 9',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.347.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_9_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 9',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.347.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_9_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 10',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.348.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_10_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 10',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.348.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_10_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 10-15',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.405.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_10_15_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 10-15',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.405.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_10_15_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 15-20',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.406.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_15_20_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 15-20',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.406.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_15_20_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 20-25',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.407.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_20_25_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 20-25',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.407.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_20_25_2019'],
  },
  {
    source: :pga,
    stat: 'Putting from 25+',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.408.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_25_2020'],
  },
  {
    source: :pga,
    stat: 'Putting from 25+',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.408.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['% made'],
    destination_column_names: ['putting_25_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 100 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02329.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 100 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02329.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 50-75 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.076.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_50_75_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 50-75 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.076.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_50_75_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 75-100 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.075.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_75_100_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 75-100 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.075.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_75_100_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 100-125 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.074.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_125_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 100-125 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.074.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_125_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 125-150 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.339.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_125_150_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 125-150 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.339.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_125_150_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 150-175 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.338.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_150_175_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 150-175 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.338.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_150_175_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 175-200 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.337.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_175_200_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 175-200 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.337.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_175_200_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 200-225 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02358.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_200_225_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 200-225 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02358.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_200_225_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 225-250 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02359.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_225_250_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 225-250 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02359.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_225_250_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 250-275 (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02360.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_250_275_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 250-275 (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02360.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_250_275_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 275+ (FW)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02361.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_275_fw_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 275+ (FW)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02361.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_275_fw_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 100 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02370.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 100 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02370.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 50-75 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02362.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_50_75_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 50-75 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02362.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_50_75_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 75-100 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02363.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_75_100_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 75-100 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02363.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_75_100_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 100-125 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02364.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_125_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 100-125 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02364.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_100_125_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 125-150 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02366.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_125_150_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 125-150 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02366.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_125_150_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 150-175 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02367.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_150_175_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 150-175 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02367.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_150_175_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 175-200 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02368.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_175_200_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 175-200 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02368.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_175_200_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 200-225 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02372.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_200_225_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 200-225 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02372.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_200_225_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 225-250 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02373.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_225_250_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 225-250 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02373.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_225_250_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 250-275 (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02374.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_250_275_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 250-275 (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02374.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_250_275_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'Approach from 275+ (RGH)',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02375.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_275_rgh_2020'],
  },
  {
    source: :pga,
    stat: 'Approach from 275+ (RGH)',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02375.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['distance'],
    source_column_names: ['avg'],
    destination_column_names: ['approach_275_rgh_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 100',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.079.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_100_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 100',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.079.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_100_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 75-100',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.078.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_75_100_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 75-100',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.078.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_75_100_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 100-125',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.077.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_100_125_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 100-125',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.077.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_100_125_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 125-150',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.329.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_125_150_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 125-150',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.329.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_125_150_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 150-175',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.328.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_150_175_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 150-175',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.328.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_150_175_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 175-200',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.327.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_175_200_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 175-200',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.327.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_175_200_2019'],
  },
  {
    source: :pga,
    stat: 'GIR from 200+',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.326.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_200_2020'],
  },
  {
    source: :pga,
    stat: 'GIR from 200+',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.326.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['gir_200_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from <10',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.369.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_10_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from <10',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.369.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_10_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 10-20',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.368.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_10_20_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 10-20',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.368.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_10_20_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 20-30',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.367.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_20_30_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 20-30',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.367.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_20_30_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 30+',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.366.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_30_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from 30+',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.366.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_30_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from rough',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.363.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_rough_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from rough',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.363.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_rough_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from sand',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.362.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_sand_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from sand',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.362.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_sand_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from other',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.365.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_other_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from other',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.365.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_other_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling from fringe',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.364.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_fringe_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling from fringe',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.364.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_fringe_2019'],
  },
  {
    source: :pga,
    stat: 'Scrambling 2020',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.130.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_2020'],
  },
  {
    source: :pga,
    stat: 'Scrambling 2019',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.130.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['scrambling_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from <5',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.068.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_5_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from <5',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.068.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_5_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 5-10',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.069.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_5_10_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 5-10',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.069.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_5_10_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 10-15',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.070.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_10_15_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 10-15',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.070.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_10_15_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 15-20',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.145.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_15_20_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 15-20',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.145.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_15_20_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 20-25',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.146.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_20_25_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt from 20-25',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.146.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_20_25_2019'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt 25+',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.147.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_25_2020'],
  },
  {
    source: :pga,
    stat: 'Avoid 3-putt 25+',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.147.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent'],
    source_column_names: ['%'],
    destination_column_names: ['avoid_3_putt_25_2019'],
  },
  {
    source: :pga,
    stat: 'Driving Distance',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.101.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float'],
    source_column_names: ['avg.'],
    destination_column_names: ['driving_distance_2020'],
  },
  {
    source: :pga,
    stat: 'Driving Distance',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.101.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float'],
    source_column_names: ['avg.'],
    destination_column_names: ['driving_distance_2019'],
  },
  {
    source: :pga,
    stat: 'Driving Accuracy',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.102.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['%', 'rank this week'],
    destination_column_names: ['driving_accuracy_2020', 'driving_accuracy_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Driving Accuracy',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.102.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['%', 'rank this week'],
    destination_column_names: ['driving_accuracy_2019', 'driving_accuracy_rank_2019'],
  },
  {
    source: :rotogrinders,
    stat: 'Odds, Salary',
    year: 2020,
    url: 'https://rotogrinders.com/articles/pga-dfs-first-look-travelers-championship-3356387',
    table_location: 'table.data-table',
    golfer_column_name: 'golfer',
    data_types: ['money', 'integer', 'string'],
    source_column_names: ['dk', 'odds', 'cuts'],
    destination_column_names: ['salary', 'odds', 'cuts'],
  },
  {
    source: :pga,
    stat: 'Around the Green',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02569.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['around_green_2020', 'around_green_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Around the Green',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02569.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['around_green_2019', 'around_green_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Par 4',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.143.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['avg', 'rank this week'],
    destination_column_names: ['par_4_2020', 'par_4_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Par 4',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.143.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['avg', 'rank this week'],
    destination_column_names: ['par_4_2019', 'par_4_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Par 5',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.144.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank', 'integer'],
    source_column_names: ['avg', 'rank this week', 'rounds'],
    destination_column_names: ['par_5_2020', 'par_5_rank_2020', 'rounds'],
  },
  {
    source: :pga,
    stat: 'Par 5',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.144.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['avg', 'rank this week'],
    destination_column_names: ['par_5_2019', 'par_5_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Off Tee',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02567.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['off_tee_2020', 'off_tee_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Off Tee',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02567.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['off_tee_2019', 'off_tee_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Putting',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02564.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['putting_2020', 'putting_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Putting',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02564.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['putting_2019', 'putting_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Tee to Green',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02674.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['tee_to_green_2020', 'tee_to_green_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Tee to Green',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02674.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['tee_to_green_2019', 'tee_to_green_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Birdie',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.352.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['birdie_2020', 'birdie_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Birdie',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.352.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['birdie_2019', 'birdie_rank_2019'],
  },
  {
    source: :pga,
    stat: 'GIR',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.103.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['%', 'rank this week'],
    destination_column_names: ['gir_2020', 'gir_rank_2020'],
  },
  {
    source: :pga,
    stat: 'GIR',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.103.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['%', 'rank this week'],
    destination_column_names: ['gir_2019', 'gir_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Approach',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02568.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['approach_2020', 'approach_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Approach',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02568.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['float', 'rank'],
    source_column_names: ['average', 'rank this week'],
    destination_column_names: ['approach_2019', 'approach_rank_2019'],
  },
  {
    source: :pga,
    stat: 'Bogey',
    year: 2020,
    url: 'https://www.pgatour.com/stats/stat.02414.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['% makes bogey', 'rank this week'],
    destination_column_names: ['bogey_2020', 'bogey_rank_2020'],
  },
  {
    source: :pga,
    stat: 'Bogey',
    year: 2019,
    url: 'https://www.pgatour.com/content/pgatour/stats/stat.02414.y2019.html',
    table_location: 'table#statsTable',
    golfer_column_name: 'player name',
    data_types: ['percent', 'rank'],
    source_column_names: ['% makes bogey', 'rank this week'],
    destination_column_names: ['bogey_2019', 'bogey_rank_2019'],
  },
]

data_sources.each do |source|
  DataSource.create(source)
end
